[package]
name = "oph"
version = "0.1.0"
edition = "2021"
publish = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
http = "1.1.0"
http-serde = "2.1.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
