[package]
name = "raw-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
oph = { path = "../../oph/" }
oph-macros = { path = "../../oph-macros/" }

[profile.release]
strip = true
opt-level = "z"
lto = true
